export const NAV_DRAWER_TOGGLE = 'NAV_DRAWER_TOGGLE';
export const APP_BAR_TITLE_CHANGE = 'APP_BAR_TITLE_CHANGE';

export const COUNTER_INCREMENT = 'COUNTER_INCREMENT';
export const COUNTER_DECREMENT = 'COUNTER_DECREMENT';
