export const TOGGLE_NAV_DRAWER = 'TOGGLE_NAV_DRAWER'
export const SET_PAGE_TITLE = 'SET_PAGE_TITLE'

export const COUNTER_INCREMENT = 'COUNTER_INCREMENT'
export const COUNTER_DECREMENT = 'COUNTER_DECREMENT'
export const COUNTER_INCREMENT_ASYNC = 'COUNTER_INCREMENT_ASYNC'
