export const SET_PAGE_TITLE = 'appLayout/SET_PAGE_TITLE'
export const TOGGLE_NAV_DRAWER = 'appLayout/TOGGLE_NAV_DRAWER'
export const TOGGLE_BACK_BUTTON = 'appLayout/TOGGLE_BACK_BUTTON'
export const CLICK_MENU_ITEM = 'appLayout/CLICK_MENU_ITEM'
export const CLICK_BACK_BUTTON = 'appLayout/CLICK_BACK_BUTTON'
export const BACK_TO_HOME = 'appLayout/BACK_TO_HOME'

export const INCREMENT = 'counter/INCREMENT'
export const DECREMENT = 'counter/DECREMENT'
export const INCREMENT_ASYNC = 'counter/INCREMENT_ASYNC'
